In [1]:
import numpy as np

In [3]:
# create target data
x = np.arange(0, 20, 1)
y = x**2
print(x)

# engineer features .
X = np.c_[x, x**2, x**3]
print(X)

y = x**2
weights = np.array([0.08, 0.54, 0.03])
print(X@weights)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[   0    0    0]
 [   1    1    1]
 [   2    4    8]
 [   3    9   27]
 [   4   16   64]
 [   5   25  125]
 [   6   36  216]
 [   7   49  343]
 [   8   64  512]
 [   9   81  729]
 [  10  100 1000]
 [  11  121 1331]
 [  12  144 1728]
 [  13  169 2197]
 [  14  196 2744]
 [  15  225 3375]
 [  16  256 4096]
 [  17  289 4913]
 [  18  324 5832]
 [  19  361 6859]]
[  0.     0.65   2.56   5.91  10.88  17.65  26.4   37.31  50.56  66.33
  84.8  106.15 130.56 158.21 189.28 223.95 262.4  304.81 351.36 402.23]
[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361]
